import 'package:flutter/material.dart';

/// Flutter icons CartIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CartIcons
///      fonts:
///       - asset: fonts/CartIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CartIcons {
  CartIcons._();

  // static const _kFontFam = 'CartIcons';

  static const IconData grocery = Icons.ac_unit;
  static const IconData account = Icons.account_balance;
  static const IconData bread = Icons.branding_watermark;
  static const IconData cart = Icons.card_giftcard;
  static const IconData favourites = Icons.favorite;
  static const IconData home = Icons.book;
  static const IconData house_hold = Icons.home;
  static const IconData liquor = Icons.account_box;
  static const IconData more = Icons.more;
}
