// Generated by https://quicktype.io
// To parse this JSON data, do
//
//     final rqModel = rqModelFromJson(jsonString);

import 'dart:convert';

List<RqModel> rqModelFromJson(String str) {
  final jsonData = json.decode(str);
  return new List<RqModel>.from(jsonData.map((x) => RqModel.fromJson(x)));
}

String rqModelToJson(List<RqModel> data) {
  final dyn = new List<dynamic>.from(data.map((x) => x.toJson()));
  return json.encode(dyn);
}

class RqModel {
  double the200;
  double the210;
  double the220;
  double the230;
  double the240;
  double the250;
  double the260;
  double the270;
  double the280;
  double the290;
  double the300;
  double the310;
  double the320;
  double the330;
  double the340;
  double the350;
  double the360;
  double the370;
  double the380;
  double the390;
  double the400;
  double the410;
  double the420;
  double the430;
  double the440;
  double the450;
  double the460;
  double the470;
  double the480;
  double the490;
  double the500;
  double gmd;

  RqModel({
    this.the200,
    this.the210,
    this.the220,
    this.the230,
    this.the240,
    this.the250,
    this.the260,
    this.the270,
    this.the280,
    this.the290,
    this.the300,
    this.the310,
    this.the320,
    this.the330,
    this.the340,
    this.the350,
    this.the360,
    this.the370,
    this.the380,
    this.the390,
    this.the400,
    this.the410,
    this.the420,
    this.the430,
    this.the440,
    this.the450,
    this.the460,
    this.the470,
    this.the480,
    this.the490,
    this.the500,
    this.gmd,
  });

  factory RqModel.fromJson(Map<String, dynamic> json) => new RqModel(
        the200: double.parse(json["200"]),
        the210: double.parse(json["210"]),
        the220: double.parse(json["220"]),
        the230: double.parse(json["230"]),
        the240: double.parse(json["240"]),
        the250: double.parse(json["250"]),
        the260: double.parse(json["260"]),
        the270: double.parse(json["270"]),
        the280: double.parse(json["280"]),
        the290: double.parse(json["290"]),
        the300: double.parse(json["300"]),
        the310: double.parse(json["310"]),
        the320: double.parse(json["320"]),
        the330: double.parse(json["330"]),
        the340: double.parse(json["340"]),
        the350: double.parse(json["350"]),
        the360: double.parse(json["360"]),
        the370: double.parse(json["370"]),
        the380: double.parse(json["380"]),
        the390: double.parse(json["390"]),
        the400: double.parse(json["400"]),
        the410: double.parse(json["410"]),
        the420: double.parse(json["420"]),
        the430: double.parse(json["430"]),
        the440: double.parse(json["440"]),
        the450: double.parse(json["450"]),
        the460: double.parse(json["460"]),
        the470: double.parse(json["470"]),
        the480: double.parse(json["480"]),
        the490: double.parse(json["490"]),
        the500: double.parse(json["500"]),
        gmd: double.parse(json["GMD"] ?? '0.00'),
      );

  Map<String, dynamic> toJson() => {
        "200": the200,
        "210": the210,
        "220": the220,
        "230": the230,
        "240": the240,
        "250": the250,
        "260": the260,
        "270": the270,
        "280": the280,
        "290": the290,
        "300": the300,
        "310": the310,
        "320": the320,
        "330": the330,
        "340": the340,
        "350": the350,
        "360": the360,
        "370": the370,
        "380": the380,
        "390": the390,
        "400": the400,
        "410": the410,
        "420": the420,
        "430": the430,
        "440": the440,
        "450": the450,
        "460": the460,
        "470": the470,
        "480": the480,
        "490": the490,
        "500": the500,
        "GMD": gmd ?? '0',
      };
  double getValue(String value) {
    switch (value) {
      case '200.0':
        return this.the200;
      case '210.0':
        return this.the210;
      case '220.0':
        return this.the220;
      case '230.0':
        return this.the230;
      case '240.0':
        return this.the240;
      case '250.0':
        return this.the250;
      case '260.0':
        return this.the260;
      case '270.0':
        return this.the270;
      case '280.0':
        return this.the280;
      case '290.0':
        return this.the290;
      case '300.0':
        return this.the300;
      case '310.0':
        return this.the310;
      case '320.0':
        return this.the320;
      case '330.0':
        return this.the330;
      case '340.0':
        return this.the340;
      case '350.0':
        return this.the350;
      case '360.0':
        return this.the360;
      case '370.0':
        return this.the370;
      case '380.0':
        return this.the380;
      case '390.0':
        return this.the390;
      case '400.0':
        return this.the400;
      case '410.0':
        return this.the410;
      case '420.0':
        return this.the420;
      case '430.0':
        return this.the430;
      case '440.0':
        return this.the440;
      case '450.0':
        return this.the450;
      case '460.0':
        return this.the460;
      case '480.0':
        return this.the480;
      case '490.0':
        return this.the490;
      case '500.0':
        return this.the500;
      default:
        return 0.00;
    }
  }
}
